[build-system]
requires = ["hatchling>=1.11.0"]
build-backend = "hatchling.build"

[project]
name = "uvicorn-denial"
version = "0.0.0"
description = "Websocket Denial Response extension for Uvicorn 🔒"
license = { text = "MIT" }
authors = [{ name = "Marcelo Trylesinski", email = "marcelotryle@gmail.com" }]
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["wsproto", "uvicorn>=0.19.0"]
